# Docker-compose version
version: '3.8'

services: 
  tf: 
    image: hashicorp/terraform:0.12.28
    volumes: 
      - .:/terraform-version-manage
    working_dir: /terraform-version-manage 
    environment:
      -AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      -AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      -AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
